from . import location
from . import ruang
from . import posisi
from . import fungsi
from . import spesifikasi 
from . import koneksi
from . import cpu
from . import ram
from . import disk
from . import merk
from . import pendidikan
from . import kelamin
from . import publish